services:
  backend:
    image: ghcr.io/ygg-drasill/penaltything/backend-dev:dev
    container_name: backend-container-dev
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    image: ghcr.io/ygg-drasill/penaltything/frontend-dev:dev
    container_name: frontend-container-dev
    networks:
      - app-network

  nginx:
    image: ghcr.io/ygg-drasill/penaltything/nginx-dev:dev
    container_name: nginx-container-dev
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge