services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-image
    container_name: backend-container
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-image
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
        - backend