services:
  backend:
    image: ghcr.io/ygg-drasill/penaltything/backend-prod:latest
    container_name: backend-container-prod
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    image: ghcr.io/ygg-drasill/penaltything/frontend-prod:latest
    container_name: frontend-container-prod
    networks:
      - app-network

  nginx:
    image: ghcr.io/ygg-drasill/penaltything/nginx-prod:latest
    container_name: nginx-container-prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge