services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    image: backend-image
    container_name: backend-container
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      network: host
      args:
        - API_TARGET=local
    image: frontend-image
    container_name: frontend-container
    ports:
      - "8080:80"
    depends_on:
        - backend