---
apiVersion: v1
kind: Service
metadata:
  name: penaltything-backend-service
spec:
  selector:
    app: penaltything-backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31356
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: penaltything-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penaltything-backend
  template:
    metadata:
      labels:
        app: penaltything-backend
    spec:
      containers:
      - name: penaltything-backend
        image: ghcr.io/Ygg-Drasill/PenaltyThing:v0.0.1
        ports:
        - containerPort: 9000