---
apiVersion: v1
kind: Service
metadata:
  name: penaltything-frontend-service
spec:
  selector:
    app: penaltything-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31355
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: penaltything-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: penaltything-frontend
  template:
    metadata:
      labels:
        app: penaltything-frontend
    spec:
      containers:
      - name: penaltything-frontend
        image: ghcr.io/Ygg-Drasill/PenaltyThing:v0.0.1
        ports:
        - containerPort: 80