definitions:
  handlers.CreateLawRequest:
    type: object
  handlers.CreateTeamRequest:
    properties:
      name:
        type: string
      userId:
        type: string
    type: object
  handlers.GetLawsRequest:
    type: object
  handlers.RegisterUserRequest:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  models.Law:
    properties:
      description:
        type: string
      id:
        type: string
      teamId:
        type: string
      title:
        type: string
    type: object
  models.Member:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  models.PenaltyEntry:
    properties:
      id:
        type: string
      law:
        $ref: '#/definitions/models.Law'
      lawId:
        type: string
      userId:
        type: string
    type: object
  models.Team:
    properties:
      id:
        type: string
      laws:
        items:
          $ref: '#/definitions/models.Law'
        type: array
      members:
        items:
          $ref: '#/definitions/models.User'
        type: array
      name:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: string
      name:
        type: string
      password:
        type: string
      penalties:
        items:
          $ref: '#/definitions/models.PenaltyEntry'
        type: array
      teamId:
        type: string
    type: object
info:
  contact: {}
paths:
  /addPenalty:
    post:
      consumes:
      - application/json
      description: register new user
      operationId: addUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Add penalty to team member
      tags:
      - penalty
  /law/create:
    post:
      consumes:
      - application/json
      description: create law
      operationId: createLaw
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateLawRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Law'
            type: array
      summary: Create new law
      tags:
      - law
  /law/getAllByTeam:
    get:
      consumes:
      - application/json
      description: get all laws in a team by teamId
      operationId: getLaws
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.GetLawsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Law'
            type: array
      summary: Get laws
      tags:
      - law
  /team/create:
    post:
      consumes:
      - application/json
      description: Create a new team
      operationId: createTeam
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateTeamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Team'
      summary: Create new team
      tags:
      - team
  /user/get:
    get:
      consumes:
      - application/json
      description: get user
      operationId: getUser
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Member'
      summary: Get user
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: register new user
      operationId: registerUser
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Add user
      tags:
      - user
swagger: "2.0"
