definitions:
  handlers.AddPenaltyRequest:
    properties:
      comment:
        type: string
      issuerUserId:
        type: string
      lawId:
        type: string
      targetUserId:
        type: string
    type: object
  handlers.CreateLawRequest:
    properties:
      description:
        type: string
      teamId:
        type: string
      title:
        type: string
    type: object
  handlers.CreateTeamRequest:
    properties:
      name:
        type: string
      userId:
        type: string
    type: object
  handlers.RegisterUserRequest:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  models.Law:
    properties:
      description:
        type: string
      id:
        type: string
      teamId:
        type: string
      title:
        type: string
    type: object
  models.Member:
    properties:
      id:
        type: string
      name:
        type: string
      penalties:
        items:
          $ref: '#/definitions/models.PenaltyEntry'
        type: array
    type: object
  models.PenaltyEntry:
    properties:
      comment:
        type: string
      createdAt:
        type: string
      id:
        type: string
      isNew:
        type: boolean
      issuedBy:
        type: string
      law:
        $ref: '#/definitions/models.Law'
      lawId:
        type: string
      userId:
        type: string
    type: object
  models.Team:
    properties:
      id:
        type: string
      laws:
        items:
          $ref: '#/definitions/models.Law'
        type: array
      members:
        items:
          $ref: '#/definitions/models.User'
        type: array
      name:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: string
      name:
        type: string
      password:
        type: string
      penalties:
        items:
          $ref: '#/definitions/models.PenaltyEntry'
        type: array
      teamId:
        type: string
    type: object
info:
  contact:
    email: tab@penaltything.me
    name: Tobias Bay
    url: http://penaltything.me/support
  title: PenaltyThing API
  version: "1.0"
paths:
  /law/create:
    post:
      consumes:
      - application/json
      description: create law
      operationId: createLaw
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateLawRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Law'
      summary: Create new law
      tags:
      - law
  /law/getByTeam:
    get:
      description: get all laws in a team by teamId
      operationId: getLaws
      parameters:
      - description: Team ID
        in: query
        name: teamId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Law'
            type: array
      summary: Get laws
      tags:
      - law
  /penalty/add:
    post:
      consumes:
      - application/json
      description: Add penalty to member of team
      operationId: addPenalty
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.AddPenaltyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PenaltyEntry'
      summary: Add penalty to team member
      tags:
      - penalty
  /team/create:
    post:
      consumes:
      - application/json
      description: Create a new team
      operationId: createTeam
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateTeamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Team'
      summary: Create new team
      tags:
      - team
  /user/get:
    get:
      description: get user
      operationId: getUser
      parameters:
      - description: User search by id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Member'
      summary: Get user
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: Register new user, given password will be encrypted on backend.
        This is subject to change
      operationId: registerUser
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Register user
      tags:
      - user
swagger: "2.0"
