basePath: /api/v1
definitions:
  models.User:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: testtesttest
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Monkey example
      tags:
      - example
swagger: "2.0"
