name: Build and Push to Prod

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build-and-push-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: Call Build
        uses: 'Ygg-Drasill/PenaltyThing/.github/workflows/build.yaml@main'
        with:
          ENVIRONMENT: "prod"
          DOCKER_TAG: ${{ github.ref }}
          token: ${{ secrets.BERTHA_TOKEN }}