name: Build and Push to Prod

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build-and-push-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
  steps:
    name: Call Build
    uses: ./.github/workflows/build.yaml
    with:
      ENVIRONMENT: "prod"
      DOCKER_TAG: ${{ github.ref }}