name: Build and Push to Dev

on:
  push:
    branches:
      - "dev"

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: Call Build
        uses: 'Ygg-Drasill/PenaltyThing/.github/workflows/build.yaml@dev'
        with:
          ENVIRONMENT: "dev"
          DOCKER_TAG: "dev"
          token: ${{ secrets.BERTHA_TOKEN }}