name: Build and Push to Dev

on:
  push:
    branches:
      - "dev"

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Call Build
        uses: ./.github/workflows/build.yaml
        with:
          ENVIRONMENT: 'dev'
          DOCKER_TAG: ''