name: Build and Push to Dev

on:
  push:
    branches:
      - "dev"

jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Call Build
        uses: ./.github/actions/build/action.yaml
        with:
          ENVIRONMENT: "dev"
          DOCKER_TAG: "dev"
          token: ${{ secrets.BERTHA_TOKEN }}