name: Build and Push to Prod

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  call-build:
    uses: ./.github/workflows/build.yaml
    with:
      ENVIRONMENT: "prod"
      DOCKER_TAG: ${{ github.ref }}